name: Deploy Jaspr to Cloudflare Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Quan trọng để có thể tạo orphan branch và chuyển branch an toàn

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: Add _redirects file for SPA routing
        run: |
          mkdir -p build/jaspr
          echo '/*    /index.html    200' > build/jaspr/_redirects

      - name: Deploy to deploy branch (for Cloudflare Pages)
        run: |
          git config user.name "huyhb"
          git config user.email "huyhbs@github.com"

          # Tạo thư mục tạm chứa build từ nhánh hiện tại
          mkdir temp-deploy
          cp -r build/jaspr/* temp-deploy/

          # Lấy version từ pubspec.yaml
          VERSION=$(grep '^version:' pubspec.yaml | cut -d ':' -f2 | cut -d '+' -f1 | xargs)
          TODAY=$(date +"%d/%m/%Y %H:%M")
          COMMIT_MSG="deploy version $VERSION - $TODAY"

          # Tạo nhánh deploy (orphan)
          git switch --orphan deploy
          git reset --hard
          git rm -rf . || true

          # Copy build từ thư mục tạm
          cp -r temp-deploy/* .

          git add .
          git commit -m "$COMMIT_MSG"
          git push origin deploy --force
