name: Deploy Jaspr to Cloudflare Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: Add _redirects file for SPA routing
        run: |
          mkdir -p build/jaspr
          echo '/*    /index.html    200' > build/jaspr/_redirects

      - name: Deploy to deploy branch (for Cloudflare Pages)
        run: |
          set -e
          git config user.name "huyhb"
          git config user.email "huyhbs@github.com"

          # Lưu commit message hiện tại
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Lưu build tạm thời
          mkdir temp-deploy
          cp -r build/jaspr/* temp-deploy/

          # Dọn dẹp mọi thay đổi để có thể checkout
          git reset --hard
          git clean -fd

          # Kiểm tra nếu nhánh deploy đã tồn tại
          if git ls-remote --exit-code --heads origin deploy; then
            git fetch origin deploy
            git checkout deploy
          else
            git checkout --orphan deploy
          fi

          # Xóa toàn bộ nội dung cũ
          git rm -rf . || true

          # Chép lại build
          cp -r temp-deploy/* .

          # Commit nếu có thay đổi
          git add .
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push origin deploy
