name: Deploy Jaspr to Cloudflare Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build Jaspr
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose

      - name: Add _redirects file for SPA routing
        run: |
          mkdir -p build/jaspr
          echo '/*    /index.html    200' > build/jaspr/_redirects

      - name: Deploy to deploy branch (Cloudflare Pages)
        run: |
          set -e  # dừng ngay nếu có lỗi

          # Setup Git
          git config user.name "huyhb"
          git config user.email "huyhbs@github.com"

          # Lưu commit message hiện tại
          COMMIT_MSG=$(git log -1 --pretty=%B)

          # Backup build folder
          mkdir temp-deploy
          cp -r build/jaspr/* temp-deploy/

          # Clean workspace để tránh lỗi khi switch branch
          git reset --hard
          git clean -fd

          # Tạo hoặc chuyển sang nhánh deploy
          if git show-ref --quiet refs/heads/deploy; then
            git checkout deploy
          else
            git checkout --orphan deploy
          fi

          # Xóa tất cả nội dung trong branch
          rm -rf *
          rm -rf .[^.]* || true  # xóa các file ẩn như .gitignore nếu có (trừ .git)

          # Copy lại build
          cp -r ../temp-deploy/* .

          # Commit nếu có thay đổi
          git add .
          git diff --cached --quiet || git commit -m "$COMMIT_MSG"

          # Push force vì nhánh deploy là độc lập
          git push origin deploy --force
